// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSv9BVyS6nLBqxMf3y0oKT44lF2K0S7OI',
    appId: '1:138985650635:web:864f8f3fe4d28f2aee5e4e',
    messagingSenderId: '138985650635',
    projectId: 'asnusatrans-340b7',
    authDomain: 'asnusatrans-340b7.firebaseapp.com',
    storageBucket: 'asnusatrans-340b7.firebasestorage.app',
    measurementId: 'G-28RT2G0D20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDowsm5_ggvlRpfyVt0NfPOm34opM4wqiU',
    appId: '1:138985650635:android:44ed7662beae6337ee5e4e',
    messagingSenderId: '138985650635',
    projectId: 'asnusatrans-340b7',
    storageBucket: 'asnusatrans-340b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1tujTLqc4SCU5hgGcfQ3VVVHcdbufBw',
    appId: '1:138985650635:ios:0f12caf81c0bfaf5ee5e4e',
    messagingSenderId: '138985650635',
    projectId: 'asnusatrans-340b7',
    storageBucket: 'asnusatrans-340b7.firebasestorage.app',
    iosBundleId: 'com.example.cvantMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1tujTLqc4SCU5hgGcfQ3VVVHcdbufBw',
    appId: '1:138985650635:ios:0f12caf81c0bfaf5ee5e4e',
    messagingSenderId: '138985650635',
    projectId: 'asnusatrans-340b7',
    storageBucket: 'asnusatrans-340b7.firebasestorage.app',
    iosBundleId: 'com.example.cvantMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSv9BVyS6nLBqxMf3y0oKT44lF2K0S7OI',
    appId: '1:138985650635:web:97cdcc9a70ddcbfaee5e4e',
    messagingSenderId: '138985650635',
    projectId: 'asnusatrans-340b7',
    authDomain: 'asnusatrans-340b7.firebaseapp.com',
    storageBucket: 'asnusatrans-340b7.firebasestorage.app',
    measurementId: 'G-237JM14N32',
  );
}
